language: python
python: 3.6
# before_install:
#   - cd monolith/
env:
  - ENV_VAR=reminder
install:
  - pip install -r requirements.txt
script:
  - python -m pytest --cov-report term-missing --cov=monolith monolith/ 
# after_success:
  # - coveralls
