language: python
python: 3.8
services:
  - docker
# env:
#   - DOCKER_COMPOSE_VERSION=1.27.4
before_install:
  - docker-compose up -d
  - bash start_celery.sh
install:
  - pip install -r requirements.txt
script:
  - python -m pytest --cov-report term-missing --cov=monolith monolith/ 
after_script:
  - docker-compose logs
  - docker-compose down
